# -*- coding: utf-8 -*-
"""Despliegue_dentalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3iASrK-3-VHllahkrbSlMaY1LaZ9BLo
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo.pkl'

modelTree,modelKnn, modelNN, modelSVM, labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_excel("Clientes_dentalyticsfuturos.xlsx")
#data.head()

#Se realiza la preparación
data_preparada=data.copy()

data_preparada = pd.get_dummies(data_preparada, columns=['Canal preferido'], drop_first=False)
data_preparada = pd.get_dummies(data_preparada, columns=['Cat preferida'], drop_first=False) #En despliegue no se borran dummies
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#hacemos la prediccion con el tree
Y_fut =modelTree.predict(data_preparada)
print(Y_fut)

data['Tree']=labelencoder.inverse_transform(Y_fut)
data.head()

data_preparada[['Ticket promedio']]=min_max_scaler.transform(data_preparada[['Ticket promedio']])
data_preparada.head()

#Hacemos la predicción con Knn
Y_fut = modelKnn.predict(data_preparada)
data['Knn']=labelencoder.inverse_transform(Y_fut)
data.head()

#Hacemos la predicción con Red Neuronal
Y_fut = modelNN.predict(data_preparada)
data['Neural_Network']=labelencoder.inverse_transform(Y_fut)
data.head()

#Hacemos la predicción con SVM
Y_fut = modelSVM.predict(data_preparada)
data['SVM']=labelencoder.inverse_transform(Y_fut)
data

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
import pandas as pd

st.title('Prediccion tipo de cliente Rapident')
Canal_preferido = st.selectbox('Canal preferido', ['Ventas digitales', 'Punto de venta'])
Ticket_promedio = st.number_input('Ticket promedio', min_value=14, max_value=52, value=20, step=1)
Acrilicos_y_flexibles = st.selectbox('Acrilicos y flexibles', ['0', '1'])
Blanqueamientos_y_profilaxis = st.selectbox('Blanqueamientos y profilaxis', ['0', '1'])
Dientes = st.selectbox('Dientes', ['0', '1'])
Equipos_y_accesorios = st.selectbox('equipos y accesorios', ['0', '1'])
Higiene_diaria = st.selectbox('higiene diaria', ['0', '1'])
Impresiones_y_vaciado = st.selectbox('impresiones y vaciado', ['0', '1'])
Instrumental_e_insumos = st.selectbox('instrumental e insumos', ['0', '1'])
Ortodoncia = st.selectbox('ortodoncia', ['0', '1'])
Restauracion = st.selectbox('Restauracion', ['0', '1'])
Laboratorio = st.selectbox('Laboratorio', ['0', '1'])
discos_y_pulidos = st.selectbox('discos y pulidos', ['0', '1'])
Desechables_y_desinfeccion = st.selectbox('Desechables y desinfeccion', ['0', '1'])
Especializacion = st.number_input(
    'Especializacion',
    min_value=0.15,
    max_value=1.0,
    value=0.5,
    step=0.01
)
Cat_preferida = st.selectbox('Cat preferida', ['Acrilicos y flexibles', 'blanqueamientos y profilaxis', 'Dientes', 'equipos y accesorios', 'higiene diaria','impresiones y vaciado','instrumental e insumos','ortodoncia','restauracion','laboratorio','discos y pulidos','desechables y desinfeccion'])

#dataframe
datos =[[Canal_preferido,Ticket_promedio,Acrilicos_y_flexibles, Blanqueamientos_y_profilaxis, Dientes, Equipos_y_accesorios, Higiene_diaria, Impresiones_y_vaciado,Instrumental_e_insumos,Ortodoncia, Restauracion,Laboratorio, discos_y_pulidos,Desechables_y_desinfeccion, Especializacion, Cat_preferida]]
data = pd.DataFrame(datos, columns=['Canal_preferido','Ticket_promedio', 'Acrilicos_y_flexibles', 'Blanqueamientos_y_profilaxis', 'Dientes', 'Equipos_y_accesorios', 'Higiene_diaria', 'Impresiones_y_vaciado', 'Instrumental_e_insumos', 'Ortodoncia', 'Restauracion', 'Laboratorio', 'discos_y_pulidos', 'Desechables_y_desinfeccion' , 'Especializacion', 'Cat_preferida'])



!pip install streamlit